global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-app:3000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']